### ISSUE TITLE
info works, but metrics throws an error

### ISSUE THREAD

**Issue by b1naryv1k1ng** [BudgetSmartHome/hubitat2prom#30]
Started this container up and I can reach the <url>:5000/info and it says connected, but when trying to go to <url>:5000/metrics I get a 500 Internal Server Error. Looking at the logs, I'm seeing the following:

 docker logs hubitat2prom
[2023-06-10 15:40:09 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2023-06-10 15:40:09 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2023-06-10 15:40:09 +0000] [1] [INFO] Using worker: sync
[2023-06-10 15:40:09 +0000] [7] [INFO] Booting worker with pid: 7
[2023-06-10 15:40:09 +0000] [8] [INFO] Booting worker with pid: 8
[2023-06-10 15:40:09 +0000] [9] [INFO] Booting worker with pid: 9
[2023-06-10 15:40:10 +0000] [10] [INFO] Booting worker with pid: 10
[2023-06-10 15:40:39,832] ERROR in app: Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 48, in metrics
    device_details = requests.get(f"{base_uri}/{device['id']}?access_token={access_token}").json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-06-10 15:40:44,422] ERROR in app: Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 48, in metrics
    device_details = requests.get(f"{base_uri}/{device['id']}?access_token={access_token}").json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-06-10 15:41:06,409] ERROR in app: Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 48, in metrics
    device_details = requests.get(f"{base_uri}/{device['id']}?access_token={access_token}").json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by b1naryv1k1ng** [comment]
I found the issue, I had the /all/ at the end of the url in the env file
